### ISSUE TITLE
Problems with J series

### ISSUE THREAD

**Issue by kkapitan** [kkapitan/homebridge-homesung#1]
Continuing the discussion started here https://github.com/tavicu/homebridge-samsung-tizen/issues/12

There are some issues with J series under investigation. 
The version **v0.1.4** is the first attempt to fix it, we'll see where it gets - but we need someone to test this since I personally do not have a J series device available.

**Comment by boro55** [comment]
@kkapitan I'm here to help with testing :)

**Comment by kkapitan** [comment]
Perfect! :) I've updated the plugin based on the logs you've provided today. Would you be so kind to try it? I've found one issue and I hope this will finally resolve it :)

**Comment by kkapitan** [comment]
Perfect!!! :D Thanks so much for your patience and persistence in testing this! We did a great job :) 
Try the "KEY_POWER" - it seems there is a difference in H and J series in that matter. 

Hope you'll have a great time using this plugin :)

**Comment by bartbovendeerdt** [comment]
Works on UE48H6410 like a charm! Also looking forward to the WOL feature!

**Comment by kkapitan** [comment]
@boro55 pozdro! Internet jest mały ;)
@bartbovendeerdt super happy to hear that!

Powering on should be ready by the weekend I hope. This depends on the time my RPI will arrive.

Since the issue is resolved - i’m going to close it. If you think this solution is good enough for wider use, feel free to leave a star to increase the visibility in npm/github. 

Thanks guys and good luck with your automation :)
