### ISSUE TITLE
Does it support Hisense TVs

### ISSUE THREAD

**Issue by timo-christ** [kkapitan/homebridge-homesung#24]
Hi,
I have a Hisense H66MEC5550, is it supported?

**Comment by kkapitan** [comment]
As someone wise once told me: RTFM

**Comment by cataliniordache** [comment]
how about H66MEC5553?

**Comment by kkapitan** [comment]
H66MEC5553 will be released as a DLC soon. For only 99.99$ and a part of your soul. Can I close the issue now?

**Comment by cataliniordache** [comment]
Ok, fair price.
