### ISSUE TITLE
Delay in array

### ISSUE THREAD

**Issue by maimbe** [kkapitan/homebridge-homesung#3]
I'm having trouble making an array, for example:

            {"name": "Open Netflix", "command": ["KEY_CONTENTS", "KEY_LEFT", "2 * KEY_ENTER", "KEY_RIGHT", "2 * KEY_ENTER"

I could not find a way to include 1 delay in the array.

**Comment by kkapitan** [comment]
Hi @maimbe, thanks for using this plugin!

Currently there is no way to include a delay between commands via config file. However this is a great feature request! I'll try to include the option to specify a global delay between commands per switch and also, as you've mentioned, per specific commands in the array. Will it solve your problem?

**Comment by kkapitan** [comment]
Hi, small update from me - my RPI arrived so I can finally work on turn on feature. 

The thing is I've got a little emergency this weekend that needs to be addressed, so the next version should be released on Monday or Tuesday.

**Comment by maimbe** [comment]
It worked very well, thank you.

About HDMI CEC I could not test because I do not have 1 HDMI cable from my PC to the Television

**Comment by maimbe** [comment]
The problem I'm having is with the "KEY_POWEROFF" button, it works the first time, but after turning on the TV with the control, the "power off switch" on my homekit will not turn on again, causing me to have to talk for "siri":

Please turn on the TV so it understands and forces the new request to "power off"

**Comment by kkapitan** [comment]
I understand, I'll see what I can do, but in general the WIFI-based power option is less accurate than hdmi-cec one. I'll try to implement some kind of a ping to periodically check if TV is on.

**Comment by maimbe** [comment]
Work fine a Delay!! Thx !!!!
