### ISSUE TITLE
homesung-pair command

### ISSUE THREAD

**Issue by markstamnl** [kkapitan/homebridge-homesung#4]
Hi!

How do i execute the homesung-pair command within homebridge. I'm running it on a rpi with docker-compose....

**Comment by kkapitan** [comment]
Hi!

If you go to the terminal and type `homesung-pair <ip of the device>` what is the output?
Can you also paste me what `echo ${PATH}` in terminal is showing?

The thing is, this command is not supposed to be executed within homebridge. It's more of a tool to help you setup the `config.json` properly for the plugin to work.

**Comment by markstamnl** [comment]
Thanks for the quick response!!

Output of echo ${PATH} is: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

And the output of the original homesung-pair command is: `/bin/sh: homesung-pair: not found`

**Comment by kkapitan** [comment]
I'm not sure how the homebridge config UI affects this, but as a workaround I would try to go to the `homebridge-homesung` plugin location (should be `/usr/local/lib/node_modules/homebridge-homesung`) and then run `./bin/pair <ip>`. 

Maybe the symlink was not created or is somehow outside of the $PATH (which is strange). Hopefully invoking this the longer way as described above will solve things.

**Comment by markstamnl** [comment]
Found the plugin location but now it says 
`/usr/bin/env: ‘node’: No such file or directory`

**Comment by markstamnl** [comment]
And if i try to run it with `sudo python ./bin/pair 192.168.2.1` it says:

`File "./bin/pair", line 3
    'use strict';
    ^
IndentationError: unexpected indent`

**Comment by markstamnl** [comment]
Nevermind found it! Had to do this all in the homebridge config ui terminal, i think because i'm running homebridge within a docker-compose container

**Comment by kkapitan** [comment]
Yeah the python fails because this is javascript code which needs to be run by node.js. Glad that you solved it :) 

Is it working now, can you connect to the TV?

**Comment by markstamnl** [comment]
Yup all fixed! Just setup the connection with my TV and everything is working great! Now playing around with al the different config options. Thanks for the help!
